org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47.4.10,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1


## Mod Properties
mod_id=flansmodultimate
mod_name=Flan's Mod Ultimate
mod_credits=Based on Flan's Mod by Jamioflan and contributors, and the legacy Flan's Mod Ultimate Stability Edition project. See the bundled license and repository attribution for details.
mod_license=CC BY-NC-SA 3.0
mod_group_id=com.flansmodultimate
mod_authors=Wolff
mod_description=Unofficial and independently maintained modern continuation/reimplementation of the Flan's Mod ecosystem, with compatibility for legacy content packs.
mod_version=2.1

packs_manager_name=Flan's Mod Ultimate Packs Manager
packs_manager_version=1.0