pluginManagement {
    repositories {
        gradlePluginPortal()
    }
    plugins {
        id 'name.remal.sonarlint' version version_sonarlint
        id 'com.diffplug.spotless' version version_spotless
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}
