license="${mod_license}"

[[mods]]
modId="${mod_id_packs}"
version="${packs_version}"
displayName="${mod_name_packs}"
authors="${mod_authors}"
description='''Bundled legacy Flan content packs for Flan's Mod Ultimate.'''

[[dependencies.${mod_id_packs}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id_packs}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id_packs}]]
modId="${mod_id}"
type="optional"
versionRange="*"
ordering="BEFORE"
side="BOTH"
