license="${mod_license}"

[[mods]]
modId="flansmodultimate_wolff_starwars"
version="3.0"
displayName="Wolff's Star Wars Content for Flan's Mod Ultimate 2"
authors="${mod_authors}"
description='''Bundled Wolff's Star Wars content pack for Flan's Mod Ultimate.'''

[[dependencies.flansmodultimate_wolff_starwars]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolff_starwars]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.flansmodultimate_wolff_starwars]]
modId="${mod_id}"
type="required"
versionRange="[${mod_version},)"
ordering="BEFORE"
side="BOTH"
