license="${mod_license}"

[[mods]]
modId="${official_packs_mod_id}"
version="${official_packs_version}"
displayName="${official_packs_mod_name}"
authors="${mod_authors}"
description='''Official legacy content packs for Flan's Mod Ultimate.'''

[[dependencies.${official_packs_mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${official_packs_mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${official_packs_mod_id}]]
modId="${mod_id}"
type="required"
versionRange="[${mod_version},)"
ordering="BEFORE"
side="BOTH"
