#contentPacksRelativePath:
#    Path to your content packs, relative to the .minecraft directory.
#forceRegenContentPacksAssetsAndIds:
#    Set to true to force asset and ids regeneration. This will increase the startup time significantly.
#    Only do this once when you modified some of your content packs (new assets or new ids).
#contentLoadingSystemVersion:
#    Version of the content loading system.
#    Will be incremented when the content loading process is undergoing significant changes.
#    When the version changes, asset and ids regeneration will be automatically performed once.
#useDefaultCategories:
#    The new category system allows items to be grouped and modified without modifying their config files in content packs.
#    Categories can apply or override settings for all items within them.
#    By default, this mod provides preconfigured categories in .minecraft/config/flansmodultimate/default.
#    Set this option to false if you want to disable these default categories.
#
#Fri May 22 16:29:23 CST 2026
contentLoadingSystemVersion=8
contentPacksRelativePath=flan
forceRegenContentPacksAssetsAndIds=false
useDefaultCategories=true
